name: "Validate and plan for pull request"

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
  validate_test:
    name: Validate test Terraform config
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/test
    secrets:
      access_key: "${{secrets.access_key_dev}}"
      secret_key: "${{secrets.secret_key_dev}}"
  validate_staging:
    name: Validate staging Terraform config
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/staging
    secrets:
      access_key: "${{secrets.access_key_dev}}"
      secret_key: "${{secrets.secret_key_dev}}"
  validate_production:
    name: Validate production Terraform config
    uses: ./.github/workflows/terraform.yml
    with:
      workdir: terraform/production
    secrets:
      access_key: "${{secrets.access_key_prod}}"
      secret_key: "${{secrets.secret_key_prod}}"
